### ISSUE TITLE
Unable to auto start and Device ID will regenerate every time reboot

### ISSUE THREAD

**Issue by a2940uw** [mwarning/zerotier-openwrt#6]
I follow the installation guide and success to compile the latest binary version 1.1.2 for my TP-Link 1043ND - OpenWrt Chaos Calmer 15.05 / LuCI (git-15.248.30277-3836b45) , I have try to enable the service to run "/etc/init.d/zerotier enable" after install complete, but when every-time reboot the OpenWRT, I check with the service status still show offline "zerotier-cli info", when I manual to start the daemon "zerotier-one -d" the device ID will regenerate a new one, the existing device ID will not be re-use and the device will need to set "allowed" in zerotier configuration webpage, sorry I still a newbie for openwrt, I don't know how to control the service to start-up properly and I not see the issue happen in other platform , such as Windows / Linux.

**Comment by mwarning** [comment]
Problem confirmed. Working on it.

**Comment by mwarning** [comment]
Should be fixed in 3e972f60327fc34c5294ad666d85af4a23e6ac93, please test.

**Comment by a2940uw** [comment]
Dear mwarning.
Download and tested the pre-build ipk, the service start error message is gone but all the issue is still appear.
Thank you

**Comment by mwarning** [comment]
May I did no understand the problem then. ZT should start when the device boots if enabled (/etc/init.d/zerotier enable).

**Comment by a2940uw** [comment]
Sorry for my bad English, I have found the zerotier daemon does not auto start when I was already enable the service and after reboot, and all the issue is no change.

**Comment by mwarning** [comment]
Can you provide instructions for me on how to reproduces the problem? It works for me.

**Comment by Aboe646** [comment]
Is this resolved? Because I have the same problem.
I can't get zerotier started thru the init-script. It won't even create the /var/lib/zerotier folder.

**Comment by mwarning** [comment]
@Aboe646: It works for me. Otherwise just provide me with instructions on how to replicate the problem.

I set enable to 1 in /etc/conf/zerotier and do "/etc/init.d/zerotier start" - ZT starts. OpenWrt version is 15.05.1

**Comment by Aboe646** [comment]
I didn't know we needed to edit the "/etc/config/zerotier" file. Now It works like a charm. Thx for your effort :)

**Comment by mwarning** [comment]
Ok, I've set enabled to 1 by default. Hope that helps.
